package sample.application.api.shared.model;

import jakarta.persistence.*;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;

/// A base class for implementing JPA Entities.
/// All classes that have the [Entity] annotation must inherit from this class.
/// Those classes have all atributes define as public, since the
/// [auto-class-accessors-maven-plugin](https://github.com/manoelcampos/auto-class-accessors-maven-plugin) is being used.
/// This way, when there is a read/write to a field,
/// the respective getter/getter is called instead (if existing).
/// The plugin is just included inside the pom.xml and the m`agic happens when the project is built.
///
/// @author Manoel Campos
@MappedSuperclass
public abstract class AbstractBaseModel implements BaseModel {
    /// Unique identifier of the object, generated by the database.
    /// `@Column(nullable = false)` indicates that the field cannot be null in the database.
    /// `@Nullable` (used in the getter in the interface) indicates that the field can be null in the application, since when inserting,
    /// the record is sent without an ID, which is generated in the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false)
    public Long id;

    public AbstractBaseModel() {
    }

    public AbstractBaseModel(final long id) {
        this.id = id;
    }

    /**
     * Safely checks for Null Pointer Exception if the entity's ID is equal to a given value.
     * @return true if the entity's ID is equal to the passed ID
     */
    public boolean isSameId(final long id){
        return this.id != null && this.id == id;
    }

    @Override public @Nullable Long getId() { return id; }

    @Override
    public String toString() {
        return "%s{id: %d}".formatted(getClass().getSimpleName(), id);
    }

    @Override
    public boolean equals(final Object that) {
        if(that.getClass() == this.getClass()){
            return Objects.equals(this.id, ((AbstractBaseModel) that).id);
        }

        return false;
    }
}
